cgr_compressor:
	g++ main.cpp compressor.hpp -o compressor -pthread -fopenmp -std=c++17
graph_sort:
	g++ graph_sort.cpp -o graph_sort -O3 -std=c++17
convert2data:
	g++ convert2data.cpp -o convert2data -O3 -std=c++17
clean:
	rm compressor
